name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install
      - run: npm run build
      
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.4.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (renovate-bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/validator.tool@${{steps.create_tag.outputs.versionNumber}}/file/README.md)

            ${{ steps.changelog.outputs.compareurl }}

            ${{ steps.changelog.outputs.changelog }}